name: errors
description: Dart package which manages app common errors.
version: 2.0.0
# homepage: https://github.com/NoScopeDevs/errors
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  very_good_analysis: ^2.0.0
  test: ^1.16.8